import 'package:flutter/material.dart';

class Categories {
  static const List<String> categories = [
    "Electronics",
    "IDs & Cards",
    "Books & Documents",
    "Cash",
    "Bags",
    "Accessories",
    "Keys & Wallets",
    "Clothing",
    "Others",
  ];
}

class categoryIcons {
  static const Map<String, IconData> icons = {
    "Electronics": Icons.devices,
    "IDs & Cards": Icons.badge,
    "Books & Documents": Icons.menu_book_outlined,
    "Cash": Icons.money_rounded,
    "Bags": Icons.work,
    "Accessories": Icons.diamond_outlined,
    "Keys & Wallets": Icons.wallet,
    "Clothing": Icons.checkroom_rounded,
    "Others": Icons.category,
  };
}

class LocationData {
  static const List<String> locations = [
    "Medical - PH1",
    "Medical - PH2",
    "Medical - PH3",
    "Medical - PH4",
    "Medical - P1",
    "Medical - P2",
    "Medical - P3",
    "Medical - D1",
    "Medical - D2",
    "Medical - D3",
    "Medical - D4",
    "Medical - N1",
    "Medical - N2",
    "Medical - N3",
    "Medical - N4",
    "Medical - M1",
    "Medical - M2",
    "Medical - M3",
    "Medical - M4",
    "Medical - M5",
    "Medical - M6",
    "Medical - Cafeteria",
    "Medical - Medical Halls",
    "Medical - Science Hall 1",
    "Medical - Science Hall 2",

    "Engineering - A1",
    "Engineering - A2",
    "Engineering - A3",
    "Engineering - A4",
    "Engineering - G1",
    "Engineering - G2",
    "Engineering - G3",
    "Engineering - G4",
    "Engineering - C1",
    "Engineering - C2",
    "Engineering - C3",
    "Engineering - C4",
    "Engineering - C5",
    "Engineering - C6",
    "Engineering - M1",
    "Engineering - M2",
    "Engineering - M3",
    "Engineering - M4",
    "Engineering - M5",
    "Engineering - M6",
    "Engineering - M7",
    "Engineering - M8",
    "Engineering - E1",
    "Engineering - E2",
    "Engineering - E3",
    "Engineering - E4",
    "Engineering - N1",
    "Engineering - N2",
    "Engineering - CH1",
    "Engineering - CH2",
    "Engineering - Cafeteria",
    "Engineering - Al Karamah Auditorium",
    "Engineering - Al Farouq Auditorium",
    "Engineering - Salah Eldeen Auditorium",
    "Engineering - Engineering workshops",
    "Engineering - Center of Excellence",

    "General - Bus Station",
    "General - The Library",
    "General - Deanship of Student Affairs",
    "General - Student Center (MALL)",
    "General - SA1",
    "General - The Mosque",
    "General - Hospital",
    "General - The Lake",
    "General - Gym & Sport Hall",
    "General - Football Stadium",
    "General - Veterinary Hospital",
    "General - Female Students' Housing",
    "General - International Students Office",
    "General - International Relations Office",
    "General - Nanotechnology Institute",
    "General - University Presidency",
    "General - Prof Sa'ad Hijazi Hall",
  ];
}
