class Categories {
  static const List<String> categories = [
    "Keys & Wallets",
    "Electronics",
    "Books/papers",
    "Accessories",
    "Bags",
    "Clothing",
    "others",
  ];
}

class LocationData {
  static final Map<String, List<String>> locationsMap = {
    "🏥 Medical Buildings": [
      "PH1",
      "PH2",
      "PH3",
      "PH4",
      "P1",
      "P2",
      "P3",
      "D1",
      "D2",
      "D3",
      "D4",
      "N1",
      "N2",
      "N3",
      "N4",
      "M1",
      "M2",
      "M3",
      "M4",
      "M5",
      "M6",
      "Cafeteria",
      "Medical Halls",
      "Science Hall 1",
      "Science Hall 2",
    ],
    "⚙️ Engineering Buildings": [
      "A1",
      "A2",
      "A3",
      "A4",
      "G1",
      "G2",
      "G3",
      "G4",
      "C1",
      "C2",
      "C3",
      "C4",
      "C5",
      "C6",
      "M1",
      "M2",
      "M3",
      "M4",
      "M5",
      "M6",
      "M7",
      "M8",
      "E1",
      "E2",
      "E3",
      "E4",
      "N1",
      "N2",
      "CH1",
      "CH2",
      "Cafeteria",
      "Al Karamah Auditorium",
      "Al Farouq Auditorium",
      "Salah Eldeen Auditorium",
      "Engineering workshops",
      "Center of Excellence for Innovative Projects",
    ],
    "🏛️ General Facilities": [
      "Bus Station",
      "The Library",
      "Deanship of Student Affairs",
      "Student Center (MALL)",
      "SA1",
      "The Mosque",
      "Hospital",
      "The Lake",
      "Gym & Sport Hall",
      "FootballStadium",
      "Veterinary Hospital",
      "Female Students' Housing",
      "International Students Office",
      "International Relations Office",
      "Nanotechnalogy Institute",
      "University Presidency",
      "Prof. Sa'ad Hijazi Hall",
    ],
  };
}
