// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGO_X_3YcZjdUl8rFL91Wc0ToPNwmPt8Q',
    appId: '1:1078239455973:web:313c403147514fd4d2020c',
    messagingSenderId: '1078239455973',
    projectId: 'just-lost-found-project',
    authDomain: 'just-lost-found-project.firebaseapp.com',
    storageBucket: 'just-lost-found-project.firebasestorage.app',
    measurementId: 'G-WWD691TYSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeFDO4ld-OLOnjid__UZlZUIB7FreXTms',
    appId: '1:1078239455973:android:bebde1a8e0591dd1d2020c',
    messagingSenderId: '1078239455973',
    projectId: 'just-lost-found-project',
    storageBucket: 'just-lost-found-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlFtTbiJshIh5ADGJXwoaxYs1O_7FNY-w',
    appId: '1:1078239455973:ios:71bd5ab65d7e71e2d2020c',
    messagingSenderId: '1078239455973',
    projectId: 'just-lost-found-project',
    storageBucket: 'just-lost-found-project.firebasestorage.app',
    iosBundleId: 'com.example.justLostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlFtTbiJshIh5ADGJXwoaxYs1O_7FNY-w',
    appId: '1:1078239455973:ios:71bd5ab65d7e71e2d2020c',
    messagingSenderId: '1078239455973',
    projectId: 'just-lost-found-project',
    storageBucket: 'just-lost-found-project.firebasestorage.app',
    iosBundleId: 'com.example.justLostAndFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGO_X_3YcZjdUl8rFL91Wc0ToPNwmPt8Q',
    appId: '1:1078239455973:web:803ac150e5e661d0d2020c',
    messagingSenderId: '1078239455973',
    projectId: 'just-lost-found-project',
    authDomain: 'just-lost-found-project.firebaseapp.com',
    storageBucket: 'just-lost-found-project.firebasestorage.app',
    measurementId: 'G-3J82MXYZ5P',
  );

}