// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV0t6F4gmW0egDF_0M8OnIvoinR7l088A',
    appId: '1:753528120603:web:1555d963c1c4327b7f5fbe',
    messagingSenderId: '753528120603',
    projectId: 'just-lost-and-found',
    authDomain: 'just-lost-and-found.firebaseapp.com',
    storageBucket: 'just-lost-and-found.firebasestorage.app',
    measurementId: 'G-KTDR4X8P4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexhkynQYIu-9acsxd_Cbtdc_4FDtqTbw',
    appId: '1:753528120603:android:52d92958fd92a1b67f5fbe',
    messagingSenderId: '753528120603',
    projectId: 'just-lost-and-found',
    storageBucket: 'just-lost-and-found.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Drb4h2kdTV1VUWWyrXKkT3Z0srpMbCc',
    appId: '1:753528120603:ios:f7f23202425cdf007f5fbe',
    messagingSenderId: '753528120603',
    projectId: 'just-lost-and-found',
    storageBucket: 'just-lost-and-found.firebasestorage.app',
    iosBundleId: 'com.example.justLostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Drb4h2kdTV1VUWWyrXKkT3Z0srpMbCc',
    appId: '1:753528120603:ios:f7f23202425cdf007f5fbe',
    messagingSenderId: '753528120603',
    projectId: 'just-lost-and-found',
    storageBucket: 'just-lost-and-found.firebasestorage.app',
    iosBundleId: 'com.example.justLostAndFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV0t6F4gmW0egDF_0M8OnIvoinR7l088A',
    appId: '1:753528120603:web:565b780327d351c17f5fbe',
    messagingSenderId: '753528120603',
    projectId: 'just-lost-and-found',
    authDomain: 'just-lost-and-found.firebaseapp.com',
    storageBucket: 'just-lost-and-found.firebasestorage.app',
    measurementId: 'G-TNK98QH5Q5',
  );
}
